import 'package:flutter/material.dart';

class OfficialMenuProvider extends ChangeNotifier {
  final List<Map> _allMenu = [
    {
      'Burger' : {
        'Roti Atas': {'qty': 1, 'price': 3000},
        'Selada' : {'qty': 1, 'price': 1000},
        'Bombai' : {'qty': 1, 'price': 2000},
        'Tomat' : {'qty': 1, 'price': 2000},
        'Keju' : {'qty': 1, 'price': 4000},
        'Telur' : {'qty': 1, 'price': 5000},
        'Sapi' : {'qty': 1, 'price': 12000},
        'Onion Ring' : {'qty': 1, 'price': 4000},
        'Bayam' : {'qty': 1, 'price': 3000},
        'Roti Bawah': {'qty': 1, 'price': 3000},
      },
      'TtlQty' : 10,
      'Discount' : 4000,
      'TtlPrice' : 35000,
      'Creator' : 'B_Kreazi Official',
      'Name' : 'Meat Deluxe',
    },
    {
      'Burger' : {
        'Roti Atas': {'qty': 1, 'price': 3000},
        'Selada' : {'qty': 1, 'price': 1000},
        'Tomat' : {'qty': 1, 'price': 2000},
        'Ayam' : {'qty': 1, 'price': 9000},
        'Onion Ring' : {'qty': 1, 'price': 4000},
        'Bayam' : {'qty': 1, 'price': 3000},
        'Roti Bawah': {'qty': 1, 'price': 3000},
      },
      'TtlQty' : 7,
      'Discount' : 3000,
      'TtlPrice' : 22000,
      'Creator' : 'B_Kreazi Official',
      'Name' : 'OG Chic',
    },
    {
      'Burger' : {
        'Roti Atas': {'qty': 1, 'price': 3000},
        'Timun' : {'qty': 1, 'price': 1000},
        'Keju' : {'qty': 1, 'price': 4000},
        'Telur' : {'qty': 1, 'price': 5000},
        'Paprika' : {'qty': 1, 'price': 5000},
        'Roti Bawah': {'qty': 1, 'price': 3000},
      },
      'TtlQty' : 6,
      'Discount' : 3000,
      'TtlPrice' : 18000,
      'Creator' : 'B_Kreazi Official',
      'Name' : 'Eggoist',
    },
    {
      'Burger' : {
        'Roti Atas': {'qty': 1, 'price': 3000},
        'Selada' : {'qty': 1, 'price': 1000},
        'Keju' : {'qty': 3, 'price': 12000},
        'Ikan' : {'qty': 1, 'price': 10000},
        'Bayam' : {'qty': 1, 'price': 3000},
        'Roti Bawah': {'qty': 1, 'price': 3000},
      },
      'TtlQty' : 8,
      'Discount' : 2000,
      'TtlPrice' : 30000,
      'Creator' : 'B_Kreazi Official',
      'Name' : 'Cheesy on Fishy',
    },
    {
      'Burger' : {
        'Roti Atas': {'qty': 1, 'price': 3000},
        'Selada' : {'qty': 1, 'price': 1000},
        'Tomat' : {'qty': 1, 'price': 2000},
        'Jamur' : {'qty': 2, 'price': 8000},
        'Bayam' : {'qty': 1, 'price': 3000},
        'Roti Bawah': {'qty': 1, 'price': 3000},
      },
      'TtlQty' : 7,
      'Discount' : 5000,
      'TtlPrice' : 15000,
      'Creator' : 'B_Kreazi Official',
      'Name' : 'I`m Vg',
    },
    {
      'Burger' : {
        'Roti Atas': {'qty': 1, 'price': 3000},
        'Bombai' : {'qty': 1, 'price': 2000},
        'Timun' : {'qty': 1, 'price': 1000},
        'Jamur' : {'qty': 1, 'price': 4000},
        'Telur' : {'qty': 1, 'price': 5000},
        'Ikan' : {'qty': 1, 'price': 10000},
        'Paprika' : {'qty': 1, 'price': 5000},
        'Roti Bawah': {'qty': 1, 'price': 3000},
      },
      'TtlQty' : 8,
      'Discount' : 3000,
      'TtlPrice' : 30000,
      'Creator' : 'B_Kreazi Official',
      'Name' : 'EggFish Pepper',  // Elvis Presly
    },
    {
      'Burger' : {
        'Roti Atas': {'qty': 1, 'price': 3000},
        'Timun' : {'qty': 1, 'price': 1000},
        'Keju' : {'qty': 1, 'price': 4000},
        'Telur' : {'qty': 1, 'price': 5000},
        'Sapi' : {'qty': 1, 'price': 12000},
        'Ayam' : {'qty': 1, 'price': 9000},
        'Ikan' : {'qty': 1, 'price': 10000},
        'Acar Timun' : {'qty': 1, 'price': 2000},
        'Onion Ring' : {'qty': 1, 'price': 4000},
        'Paprika' : {'qty': 1, 'price': 5000},
        'Roti Bawah': {'qty': 1, 'price': 3000},
      },
      'TtlQty' : 11,
      'Discount' : 2000,
      'TtlPrice' : 56000,
      'Creator' : 'B_Kreazi Official',
      'Name' : 'Weirdo Combo',
    },
    {
      'Burger' : {
        'Roti Atas': {'qty': 1, 'price': 3000},
        'Selada' : {'qty': 1, 'price': 1000},
        'Tomat' : {'qty': 1, 'price': 2000},
        'Timun' : {'qty': 1, 'price': 1000},
        'Keju' : {'qty': 1, 'price': 4000},
        'Sapi' : {'qty': 1, 'price': 12000},
        'Ikan' : {'qty': 1, 'price': 10000},
        'Roti Bawah': {'qty': 1, 'price': 3000},
      },
      'TtlQty' : 8,
      'Discount' : 1000,
      'TtlPrice' : 35000,
      'Creator' : 'B_Kreazi Official',
      'Name' : 'SeaLand Protein',
    },
    {
      'Burger' : {
        'Roti Atas': {'qty': 1, 'price': 3000},
        'Bombai' : {'qty': 1, 'price': 2000},
        'Tomat' : {'qty': 1, 'price': 2000},
        'Telur' : {'qty': 1, 'price': 5000},
        'Ayam' : {'qty': 1, 'price': 9000},
        'Roti Bawah': {'qty': 1, 'price': 3000},
      },
      'TtlQty' : 6,
      'Discount' : 1000,
      'TtlPrice' : 23000,
      'Creator' : 'B_Kreazi Official',
      'Name' : 'Ol_rOund', // bulat" = all round
    },
    {
      'Burger' : {
        'Roti Atas': {'qty': 1, 'price': 3000},
        'Selada' : {'qty': 1, 'price': 1000},
        'Tomat' : {'qty': 1, 'price': 2000},
        'Keju' : {'qty': 1, 'price': 4000},
        'Sapi' : {'qty': 1, 'price': 12000},
        'Ayam' : {'qty': 1, 'price': 9000},
        'Bayam' : {'qty': 1, 'price': 3000},
        'Roti Bawah': {'qty': 1, 'price': 3000},
      },
      'TtlQty' : 8,
      'Discount' : 2000,
      'TtlPrice' : 35000,
      'Creator' : 'B_Kreazi Official',
      'Name' : 'Chickin Moo',
    },
    {
      'Burger' : {
        'Roti Atas': {'qty': 1, 'price': 3000},
        'Bombai' : {'qty': 1, 'price': 2000},
        'Jamur' : {'qty': 1, 'price': 4000},
        'Telur' : {'qty': 1, 'price': 5000},
        'Onion Ring' : {'qty': 1, 'price': 4000},
        'Bayam' : {'qty': 1, 'price': 3000},
        'Paprika' : {'qty': 1, 'price': 5000},
        'Roti Bawah': {'qty': 1, 'price': 3000},
      },
      'TtlQty' : 8,
      'Discount' : 4000,
      'TtlPrice' : 25000,
      'Creator' : 'B_Kreazi Official',
      'Name' : 'Mana Meat?',
    },
    
  ];
  List<Map> get allMenu => _allMenu;
}